export const SET_IS_USER_AUTENTICATED = "SET_IS_USER_AUTENTICATED";
export const SET_LOGIN_DATA = 'SET_LOGIN_DATA';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_FAILED = 'SET_LOGIN_FAILED';


