export const SET_IS_USER_AUTENTICATED = "SET_IS_USER_AUTENTICATED";
// export const SET_LOGIN_DATA = 'SET_LOGIN_DATA';
export const SET_LOGIN_DATA_ON_SUCCESS = 'SET_LOGIN_DATA_ON_SUCCESS';
export const SET_LOGIN_DATA_ON_FAILED = 'SET_LOGIN_DATA_ON_FAILED';
export const SET_TOKEN_EXPIRED_STATUS = "SET_TOKEN_EXPIRED_STATUS";

// profile
export const SET_USER_VIEW_PROFILE_DATA = "SET_USER_VIEW_PROFILE_DATA";
export const SET_USER_PROFILE_VALIDATION_KEYS = "SET_USER_PROFILE_VALIDATION_KEYS";

export const SET_IS_REDEEM_VERIFIED = "SET_IS_REDEEM_VERIFIED";

