
export const SET_SAVE_TAX_INVESTMENT_TYPE_SUCCESS = 'SET_SAVE_TAX_INVESTMENT_TYPE_SUCCESS';
export const SET_SAVE_TAX_INVESTMENT_TYPE_FAILED = 'SET_SAVE_TAX_INVESTMENT_TYPE_FAILED';


export const SET_SAVE_TAX_CALCULATE_SUCCESS = 'SET_SAVE_TAX_CALCULATE_SUCCESS';
export const SET_SAVE_TAX_CALCULATE_FAILED = 'SET_SAVE_TAX_CALCULATE_FAILED';

export const SET_MODULE_DEFAULT_LIST_SUCCESS = 'SET_MODULE_DEFAULT_LIST_SUCCESS';
export const SET_MODULE_DEFAULT_LIST_FAILED = 'SET_MODULE_DEFAULT_LIST_FAILED';

export const SET_SAVETAX_GENRATE_SUCCESS = 'SET_SAVETAX_GENRATE_SUCCESS';
export const SET_SAVETAX_GENRATE_FAILED = 'SET_SAVETAX_GENRATE_FAILED';

export const SET_SAVETAX_LIST_SUCCESS = 'SET_SAVETAX_LIST_SUCCESS';
export const SET_SAVETAX_LIST_FAILED = 'SET_SAVETAX_LIST_FAILED';