import { meria } from "../Assets";

export const AllHolding = [
    {
        logo: meria,
        name: "Mirae Assest Dynamic Bond",
        cap: "Large Cap",
        type: "Equity",
        price: "30,000",
        invested: "1,25,000",
        year3: "",
        current: "1,46,625",
        year5: "21,625",
        absolute: "",
        margin:"17.36",
        result:"profit"
    },
    {
        logo: meria,
        name: "SBI Equity",
        cap: "Mid Cap",
        type: "Debt",
        price: "30,000",
        invested: "25,000",
        year3: "97,382",
        current: "",
        year5: "14,323",
        absolute: "",
        margin:"24.36",
        result:"profit"
    },
    {
        logo: meria,
        name: "ICICI Fund",
        cap: "Small Cap",
        type: "Balanced",
        price: "40,000",
        invested: "1,43,000",
        year3: "",
        current: "1,46,232",
        year5: "",
        absolute: "-4,214",
        margin:"03.36",
        result:"loss"
    },
    {
        logo: meria,
        name: "Mirae Assest Dynamic Bond",
        cap: "Large Cap",
        type: "Equity",
        price: "30,000",
        invested: "1,25,000",
        year3: "",
        current: "1,46,625",
        year5: "21,625",
        absolute: "",
        margin:"17.36",
        result:"profit"
    },
    {
        logo: meria,
        name: "Mirae Assest Dynamic Bond",
        cap: "Large Cap",
        type: "Equity",
        price: "30,000",
        invested: "1,25,000",
        year3: "",
        current: "1,46,625",
        year5: "21,625",
        absolute: "",
        margin:"17.36",
        result:"profit"
    },
    {
        logo: meria,
        name: "Mirae Assest Dynamic Bond",
        cap: "Large Cap",
        type: "Equity",
        price: "30,000",
        invested: "1,25,000",
        year3: "",
        current: "1,46,625",
        year5: "21,625",
        absolute: "",
        margin:"17.36",
        result:"profit"
    },
    {
        logo: meria,
        name: "Mirae Assest Dynamic Bond",
        cap: "Large Cap",
        type: "Equity",
        price: "30,000",
        invested: "1,25,000",
        year3: "",
        current: "1,46,625",
        year5: "21,625",
        absolute: "",
        margin:"17.36",
        result:"profit"
    },
    {
        logo: meria,
        name: "SBI Equity",
        cap: "Mid Cap",
        type: "Debt",
        price: "30,000",
        invested: "25,000",
        year3: "97,382",
        current: "",
        year5: "14,323",
        absolute: "",
        margin:"24.36",
        result:"profit"
    },
    {
        logo: meria,
        name: "ICICI Fund",
        cap: "Small Cap",
        type: "Balanced",
        price: "40,000",
        invested: "1,43,000",
        year3: "",
        current: "1,46,232",
        year5: "",
        absolute: "-4,214",
        margin:"03.36",
        result:"loss"
    },
    {
        logo: meria,
        name: "ICICI Fund",
        cap: "Small Cap",
        type: "Balanced",
        price: "40,000",
        invested: "1,43,000",
        year3: "",
        current: "1,46,232",
        year5: "",
        absolute: "-4,214",
        margin:"03.36",
        result:"loss"
    },
]