import { meria } from "../Assets";

export const SIP = [
    {
        logo: meria,
        name: "Mirae Asset Dynamic Bond Fund Direct Growth",
        order: 'INF209K01090',
        cap: "Large Cap",
        mandate: true,
        SIPDate: "15th of every month",
        type: "Equity",
        SIPAmount : '₹2,000',
        status:"Active",
        stopDate: "",
    },
    {
        logo: meria,
        name: "Mirae Asset Dynamic Bond Fund Direct Growth",
        order: 'INF209K01090',
        cap: "Large Cap",
        mandate: false,
        SIPDate: "15th of every month",
        type: "Equity",
        SIPAmount : '₹2,000',
        status:"Active",
        stopDate: "",
    },
    {
        logo: meria,
        name: "Mirae Asset Dynamic Bond Fund Direct Growth",
        order: 'INF209K01090',
        cap: "Small Cap",
        mandate: false,
        SIPDate: "15th of every month",
        type: "Equity",
        SIPAmount : '₹2,000',
        status:"Awaited",
        stopDate: "25 Nov, 2022",
    },
    {
        logo: meria,
        name: "Mirae Asset Dynamic Bond Fund Direct Growth",
        order: 'INF209K01090',
        cap: "Small Cap",
        mandate: false,
        SIPDate: "15th of every month",
        type: "Equity",
        SIPAmount : '₹2,000',
        status:"Stopped",
        stopDate: "12 Nov, 2022",
    },
]