import { meria } from "../Assets";

export const Transactions = [
    {
        logo: meria,
        name: "Mirae Asset Dynamic Bond Fund Direct Growth",
        date: '29 Apr',
        id: 'INF209K01090',
        confirm: true,
        mandate: true,
        transaction: false,
        reject: false,
        price: "30,000",
        SIPDate: "15th of every month",
        year3: "20.8%",
        margin:"(+17.36%)",
        result:"profit",
        type: "B",
        SIPAmount : '₹2,000',
        month:"april"
    },
    {
        logo: meria,
        name: "Mirae Asset Dynamic Bond Fund Direct Growth",
        date: '29 Apr',
        id: 'INF209K01090',
        confirm: false,
        mandate: false,
        transaction: true,
        reject: false,
        price: "30,000",
        SIPDate: "15th of every month",
        year3: "20.8%",
        margin:"(+17.36%)",
        result:"profit",
        type: "B",
        SIPAmount : '₹2,000',
        month:"april"
    },
    {
        logo: meria,
        name: "Mirae Asset Dynamic Bond Fund Direct Growth",
        date: '29 Apr',
        id: 'INF209K01090',
        confirm: false,
        mandate: false,
        transaction: false,
        reject: true,
        price: "30,000",
        SIPDate: "15th of every month",
        year3: "20.8%",
        margin:"(+17.36%)",
        result:"profit",
        type: "B",
        SIPAmount : '₹2,000',
        month: "march"
    },
    {
        logo: meria,
        name: "Mirae Asset Dynamic Bond Fund Direct Growth",
        date: '29 Apr',
        id: 'INF209K01090',
        confirm: false,
        mandate: false,
        transaction: true,
        reject: false,
        price: "30,000",
        SIPDate: "15th of every month",
        year3: "20.8%",
        margin:"(+17.36%)",
        result:"profit",
        type: "R",
        SIPAmount : '₹2,000',
        month: "march"
    },
    {
        logo: meria,
        name: "Mirae Asset Dynamic Bond Fund Direct Growth",
        date: '29 Apr',
        id: 'INF209K01090',
        confirm: false,
        mandate: false,
        transaction: false,
        reject: true,
        price: "30,000",
        SIPDate: "15th of every month",
        year3: "20.8%",
        margin:"(+17.36%)",
        result:"profit",
        type: "B",
        SIPAmount : '₹2,000',
        month: "march"
    },
]