export const SET_INITIAL_PAYMENT_DATA = "SET_INITIAL_PAYMENT_DATA";
export const SET_PORTFOLIO_LIST_DATA_IN_HOLDINGS = "SET_PORTFOLIO_LIST_DATA_IN_HOLDINGS";
export const SET_ORDER_REDEEM_DATA = "SET_ORDER_REDEEM_DATA"