export const SET_LOGIN_STATE="SET_LOGIN_STATE"
export const SET_VERIFY_STATE="SET_VERIFY_STATE"
export const SET_SIGNUPLOAD_STATE ="SIGNATURE_UPLOAD_SUCCESS"
export const SET_EDIT_STATE = "SET_EDIT_STATE"
