
export const SET_TERM_DATA_SUCCESS = 'SET_TERM_DATA_SUCCESS';
export const SET_TERM_DATA_FAILED = 'SET_TERM_DATA_FAILED';

export const SET_TERM_GENERATE_SUCCESS = 'SET_TERM_GENERATE_SUCCESS';
export const SET_TERM_GENERATE_FAILED = 'SET_TERM_GENERATE_FAILED';

export const SET_TERM_LIST_SUCCESS = 'SET_TERM_LIST_SUCCESS';
export const SET_TERM_LIST_FAILED = 'SET_TERM_LIST_FAILED';

export const SET_TERM_PURCHASE_SUCCESS = 'SET_TERM_PURCHASE_SUCCESS';
export const SET_TERM_PURCHASE_FAILED = 'SET_TERM_PURCHASE_FAILED';

export const SET_ULIP_RETURN_SUCCESS = 'SET_ULIP_RETURN_SUCCESS';
export const SET_ULIP_RETURN_FAILED = 'SET_ULIP_RETURN_FAILED';

export const SET_ULIP_GENERATE_SUCCESS = 'SET_ULIP_GENERATE_SUCCESS';
export const SET_ULIP_GENERATE_FAILED = 'SET_ULIP_GENERATE_FAILED';

export const SET_ULIP_LIST_SUCCESS = 'SET_ULIP_LIST_SUCCESS';
export const SET_ULIP_LIST_FAILED = 'SET_ULIP_LIST_FAILED';

export const SET_ULIP_SCHEME_DETAIL_SUCCESS = 'SET_ULIP_SCHEME_DETAIL_SUCCESS';
export const SET_ULIP_SCHEME_DETAIL_FAILED = 'SET_ULIP_SCHEME_DETAIL_FAILED';