export const SET_TERM_PURCHASE_SUCCESS = 'SET_TERM_PURCHASE_SUCCESS';
export const SET_TERM_PURCHASE_FAILED = 'SET_TERM_PURCHASE_FAILED';

export const SET_ULIP_RETURN_SUCCESS = 'SET_ULIP_RETURN_SUCCESS';
export const SET_ULIP_RETURN_FAILED = 'SET_ULIP_RETURN_FAILED';