export const SET__DISABLE_BUTTON = 'SET__DISABLE_BUTTON'
export const SET__LOADING = 'SET__LOADING';

//home
export const SET_BANNER_LIST_DATA = "SET_BANNER_LIST_DATA"

//profile
export const SET_STATE_LIST = "SET_STATE_LIST"
export const SET_CITY_LIST = "SET_CITY_LIST"
export const SET_INCOMESLAB_LIST = "SET_INCOMESLAB_LIST";

//
export const SET_COMMON_MSG = "SET_COMMON_MSG"
export const SET_MASTER_FUND_LIST  ="SET_MASTER_FUND_LIST"
export const SET_PROFILE_IMAGE ="SET_PROFILE_IMAGE"